---
- name: Install logcheck
  package:
    name: logcheck
    state: present

- name: create temporary directory
  tempfile:
    state: directory
    suffix: logcheck
  register: logcheck_tempdir
  delegate_to: localhost
  run_once: True
  vars:
    ansible_become: False
  changed_when: false
  tags: logcheck-copy-custom-rules

- name: Create local archive of logcheck configuration files
  archive:
    path: "{{ item.path }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    format: gz
  with_items:
    - path: "{{ role_path }}/files/ignore.d.server/"
      dest: "{{ logcheck_tempdir.path }}/ignore.tar.gz"
    - path: "{{ role_path }}/files/violations.ignore.d/"
      dest: "{{ logcheck_tempdir.path }}/violations.tar.gz"
  delegate_to: localhost
  run_once: True
  vars:
    ansible_become: False
  changed_when: false
  tags: logcheck-copy-custom-rules

- name: Copy logcheck configuration files
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - src: "{{ logcheck_tempdir.path }}/ignore.tar.gz"
      dest: "/etc/logcheck/ignore.d.server/"
    - src: "{{ logcheck_tempdir.path }}/violations.tar.gz"
      dest: "/etc/logcheck/violations.ignore.d/"
  tags: logcheck-copy-custom-rules

- name: Remove local archive of logcheck configuration files
  file:
    state: absent
    path: "{{ logcheck_tempdir.path }}"
  delegate_to: localhost
  run_once: True
  vars:
    ansible_become: False
  changed_when: false
  tags: logcheck-copy-custom-rules

- name: Copy host local rules
  copy:
    dest: "{{ item.dest }}"
    content: "{{ item.content }}"
    mode: 0644
  with_items:
    - content: "{{ logcheck_server_local_rules }}"
      dest: "/etc/logcheck/ignore.d.server/local-local"
    - content: "{{ logcheck_violation_local_rules }}"
      dest: "/etc/logcheck/violations.ignore.d/local-local"
  tags: logcheck-copy-custom-rules
  when: logcheck_server_local_rules or logcheck_violation_local_rules

- name: Configure crontab
  template:
    src: "etc/cron.d/logcheck.j2"
    dest: "/etc/cron.d/logcheck"
    owner: "root"
    group: "root"
    mode: "0644"
